### PR TITLE
feat(api): added hunter.io integration

### LINKED ISSUE #207: [2JH] hunter.io integration
## Describe the issue
Add a route that will fetch [email format for a specific domain](https://hunter.io/domain-search).
It would also be nice to integrate [email finder](https://hunter.io/email-finder) if API is available.

### PR DESCRIPTION
**Pull request by hamid-yg**
# Description

Hunter.io api integration

# Fixes

#207 

- fixes #0

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added @vrn-sh/members to the reviewers, or specific members of the team
- [x] I have added the needed labels
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [x] I have updated the README and other relevant documents (guides...)

# Additional comments

It's not definitive. I will update this pr

### CODE REVIEW

**Comment by hamid-yg** [comment]
For the route, where should I put it ? Should I create a specific route `hunter` or the calls will belong to /team or something else ?

**Review by djnnvx — APPROVED** [review]
Looks good! 

Can you please add unit tests & an endpoint that the front can reach ? 
I'm thinking of just one `/hunt` endpoint that would group those three calls ? If this is not convenient for you, you can implement it another way

**Review by djnnvx — APPROVED** [review]
this looks OK. Please fix the action & we can merge this! :fire: 

Fix seems pretty trivial, i think you just have to update the dockerfile:
```bash
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-dev-is-python3
```

**Comment by hamid-yg** [comment]
Don't merge it yet. I still need to test it manually as soon as I run the back locally to be sure that everything is working.

**Comment by djnnvx** [comment]
> Don't merge it yet. I still need to test it manually as soon as I run the back locally to be sure that everything is working.

ok! Please let me know when it's ready

**Comment by djnnvx** [comment]
is it ready @blacky-yg ?

**Pull request merged**
